<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Why-Python?" data-toc-modified-id="Why-Python?-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Why Python?</a></span><ul class="toc-item"><li><span><a href="#Python-vs.-Matlab" data-toc-modified-id="Python-vs.-Matlab-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Python vs. Matlab</a></span><ul class="toc-item"><li><span><a href="#Advantages:" data-toc-modified-id="Advantages:-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Advantages:</a></span></li><li><span><a href="#Disadvantages" data-toc-modified-id="Disadvantages-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>Disadvantages</a></span></li></ul></li><li><span><a href="#Python-vs.-Compiled-(C++,-Fortran):" data-toc-modified-id="Python-vs.-Compiled-(C++,-Fortran):-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Python vs. Compiled (C++, Fortran):</a></span><ul class="toc-item"><li><span><a href="#Advantages:" data-toc-modified-id="Advantages:-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Advantages:</a></span></li><li><span><a href="#Disadvantages:" data-toc-modified-id="Disadvantages:-1.2.2"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>Disadvantages:</a></span></li></ul></li></ul></li><li><span><a href="#Python-&quot;packages&quot;" data-toc-modified-id="Python-&quot;packages&quot;-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Python "packages"</a></span></li><li><span><a href="#Defining-Functions" data-toc-modified-id="Defining-Functions-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Defining Functions</a></span></li><li><span><a href="#Classes,-attributes,-and-methods" data-toc-modified-id="Classes,-attributes,-and-methods-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Classes, attributes, and methods</a></span></li><li><span><a href="#Reading-in-data" data-toc-modified-id="Reading-in-data-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Reading in data</a></span></li><li><span><a href="#Plotting-data" data-toc-modified-id="Plotting-data-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Plotting data</a></span></li><li><span><a href="#Integrated-Development-Environments-(IDE's)" data-toc-modified-id="Integrated-Development-Environments-(IDE's)-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Integrated Development Environments (IDE's)</a></span></li><li><span><a href="#Python-&quot;gotchas&quot;" data-toc-modified-id="Python-&quot;gotchas&quot;-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Python "gotchas"</a></span><ul class="toc-item"><li><span><a href="#Tabs-and-spaces" data-toc-modified-id="Tabs-and-spaces-8.1"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>Tabs and spaces</a></span></li><li><span><a href="#Numpy-array-copying" data-toc-modified-id="Numpy-array-copying-8.2"><span class="toc-item-num">8.2&nbsp;&nbsp;</span>Numpy array copying</a></span></li><li><span><a href="#Integer-type-casting" data-toc-modified-id="Integer-type-casting-8.3"><span class="toc-item-num">8.3&nbsp;&nbsp;</span>Integer type casting</a></span></li></ul></li></ul></div>

# Python Basics

This course will utilize the Python programming language. Some of you may be familiar with Python, but others may have only worked with Matlab. Python is similar to Matlab, but there are a few key differences and transitioning can take some effort. There is a nice [guide available for transitioning from MATLAB to Python](https://www.enthought.com/wp-content/uploads/Enthought-MATLAB-to-Python-White-Paper.pdf) which is strongly recommended for students who have not worked with Python before. The [Introduction to Python Programming](https://nbviewer.jupyter.org/github/jrjohansson/scientific-python-lectures/blob/master/Lecture-1-Introduction-to-Python-Programming.ipynb) from Johansson is also a great place to start. We will not spend a lot of lecture time specifically discussing Python, but this lecture will introduce some important ideas and provide examples for using Python in data analytics. 

If you are new to Python, the learning curve may feel very steep. However, we will hold additional help sessions, and encourage you to search internet resources like [Stack Overflow](https://stackoverflow.com/) and the official [Python tutorial](https://docs.python.org/3.6/tutorial/index.html) or work with more experienced students to learn.

## Why Python?

- Python is commonly used for data analysis, and is growing rapidly
- Python is a full programming language

### Python vs. Matlab

#### Advantages:
 - Flexibility and portability
 - Free and open source
 - Huge and supportive community
 
#### Disadvantages
 - Speed and efficiency
 - Hard to install and manage versions
 - No integrated IDE (see Spyder, etc.)
 
### Python vs. Compiled (C++, Fortran):

#### Advantages:
 - Fast development time
 - Easy to read/write/maintain
 
#### Disadvantages:
 - Speed/efficiency

## Python "packages"

Unlike Matlab, Python is organized into "packages" that contain different types of functionality. There is a ["standard library"](https://docs.python.org/3/library/) that is available in any Python installation. This includes some basic features like math, but the functions (or libraries) still have to be imported:

In [1]:
import math

print(math.exp(1))

2.718281828459045


Functions from packages can also be directly imported:

In [2]:
from math import exp

print(exp(1))

2.718281828459045


There are also some non-standard packages that have been created by users as unofficial add-ons. One of the most widely used is the ["numpy"](https://numpy.org/) "numerical python" package, which has a number of numerical and linear algebra functions built in. We will use it extensively in this course, and it will almost always be imported using an "alias" of "np":

In [3]:
import numpy as np

A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In numpy, matrices are called "arrays". One major difference between numpy and Matlab is that numpy defaults to **elementwise operations** while Matlab defaults to matrix/vector operations.

In [4]:
B = np.array([[2,2],[2,2]])

A*B

array([[2, 4],
       [6, 8]])

Matrix/vector operations can be done using the `dot` function, or the `@` symbol:

In [5]:
C = np.dot(A,B)
C

array([[ 6,  6],
       [14, 14]])

In [6]:
D = A@B
D

array([[ 6,  6],
       [14, 14]])

Indexing arrays is similar to Matlab with 3 major exceptions:

- square brackets ('[]') are used instead of parentheses
- indexing starts from 0 instead of 1
- negative indexes are allowed (-1 is `end`)

In [11]:
A[0,0]
X = np.array([[1.,2.,3.],[4, 5]])
X

array([list([1.0, 2.0, 3.0]), list([4, 5])], dtype=object)

The `:` operator can be used to take "slices" of matrices, similar to Matlab with the syntax of:

`start:end`

or

`start:end:step`

In [21]:
a_col = A[:,0]
a_col_2 = a_col.reshape(-1, 1)
a_col_2.shape
A_2 = A.reshape(4,1)
print("A matrix: {}".format(A_2))
a_col

A matrix: [[1]
 [2]
 [3]
 [4]]


array([1, 3])

There is a very useful [Matlab/Numpy cheat sheet](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html) that can help you get up to speed quickly.

## Defining Functions

Function definitions in Python are similar to Matlab, but there are some syntax differences. Python is much more flexible about how arguments are passed. Functions take 2 types of arguments: positional arguments and keyword arguments. Positional arguments are always required and must be passed in order, while keyword arguments are optional and do not have to be passed in order. We can look at a quick example:

In [23]:
def gaussian(x, mean=0, stdev=1.0):
    g = exp(-(x-mean)**2/(2*stdev**2))
    return g

print(gaussian(0.5))
print(gaussian(0.5, 0))
print(gaussian(0.5, stdev=1, mean=0))
print(gaussian(0.5, 0, 1))

0.8824969025845955
0.8824969025845955
0.8824969025845955
0.8824969025845955


Functions are ended by "returning" a variable. If nothing is explicitly returned, the function will automatically return `None`.

In [26]:
def null_function():
    x = 5 #none of
    y = x**2 #this code
    z = exp(-y) #matters
    #if nothing is returned
    print(x)
    #return x
    
new_var = null_function()
print(new_var)

5
None


You will not have to write too many functions from scratch in this class, but will often need to modify existing functions so you should be familiar with how they work. If you do learn to write functions it can save you a lot of coding!

## Classes, attributes, and methods

Another significant difference between Matlab and Python is that Python is (very) "object oriented". This means that variables in Python are "objects" defined by an associated "class". We will not discuss how to create classes or exploit this feature of Python, but you will need to interact with many different kinds of classes that have been created by others, so it is important to be familiar with the concept.

In Python, each "object" or variable has functions and variables associated with it. A function associated with an object is called a "method", and a variable associated with an object is called an "attribute". You can see the attributes and methods of an object using the `dir` function:

In [27]:
dir(A)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

The methods/attributes beginning/ending with `__` are "private", and you generally should not mess with them unless you know Python well. The others are often very useful ways to analyze or work with the variable. The `shape` attribute of a `numpy` array is very useful, since it tells you the dimensions of the matrix:

In [28]:
A.shape

(2, 2)

The `mean` and `std` methods are useful ways to quickly find the mean and standard deviation of a matrix:

In [32]:
print(A.mean())
print(A.std())

np.mean(A)
type(A)

2.5
1.118033988749895


numpy.ndarray

In [35]:
L = [[0, 1,],[2, 3]]
L@L

TypeError: unsupported operand type(s) for @: 'list' and 'list'

Objects, functions, and variables often have associated documentation built right in. You can see this using the `help` function, which is another great way to try to make sense of what is happening and find out more about how to use a method:

In [36]:
help(A.mean)

Help on built-in function mean:

mean(...) method of numpy.ndarray instance
    a.mean(axis=None, dtype=None, out=None, keepdims=False)
    
    Returns the average of the array elements along given axis.
    
    Refer to `numpy.mean` for full documentation.
    
    See Also
    --------
    numpy.mean : equivalent function



In [37]:
A.mean(axis=1)

array([1.5, 3.5])

## Reading in data

This is a data analysis course, so it is common that you will have to read in different types of data. The `pandas` package is particularly useful for this. It has many helpful features that we will discuss throughout the course, but for now we will just show how to read in a .csv file and convert it into a numpy array.

In [38]:
import pandas as pd

df = pd.read_csv("data/ethanol_IR.csv")
df

wavenumber [cm^-1]  absorbance
0            461.563000       0.015
1            466.250502       0.014
2            470.938003       0.014
3            475.625505       0.014
4            480.313007       0.013
..                  ...         ...
709         3785.001735       0.001
710         3789.689237       0.001
711         3794.376738       0.000
712         3799.064240       0.000
713         3803.751742       0.000

[714 rows x 2 columns]

In [39]:
X = df.values
X.shape

(714, 2)

In [40]:
X[2,:]

array([4.70938003e+02, 1.40000000e-02])

## Plotting data

Plotting data in Python is also similar to Matlab, and the main library, `matplotlib` is designed to work similarly. It is rather powerful, but can also be clunky. In particular, plots cannot be easily edited after they are generated, so all modifications must be done using code. There is a [gallery of Matplotlib examples](https://matplotlib.org/gallery.html), along with associated source code, that can be very useful if you want to create fancier plots.

Typically we will make very simple plots in this course. An example of the `ethanol_IR.csv` dataset is provided below:

In [ ]:
%matplotlib inline
#from matplotlib import pylab as plt # This is the long way to do it
import pylab as plt #a much shorter but equivalent import

x = X[:,0] #take the first column as independent variable
y = X[:,1] #take the second column as dependent variable

fig, ax = plt.subplots(figsize=(10,5)) #create a new figure object (fig) with an associated axis object (ax)
ax.plot(x,y,color='r')
ax.set_xlabel('Wavenumber [cm$^{-1}$]')
ax.set_ylabel('Absorbance [unitless]')

## Integrated Development Environments (IDE's)

In this course we will use Jupyter Notebooks (like this one) to display code and submit homeworks. However, these can be a difficult way to learn Python if you aren't familiar. It can be much easier to use an IDE like "Spyder" to learn, since it will make Python feel more like Matlab. You can use Spyder (or another IDE) to write code and copy/paste it into Jupyter notebooks to turn it in.

Another useful tip is that Jupyter notebooks can be exported as `.py` files (`File -> Download as -> .py`), which you can then open in Spyder.

## Python "gotchas"

Python is great once you get used to it, and is generally very similar to Matlab and other scripting languages. However, there are a number of very tricky things that can cause issues and lots of frustration. I will collect the most insidious "gotchas" that come up in the course here in this notebook throughout the semester. If you have one to add, please let an instructor or teaching assistant know and we can include it.

### Tabs and spaces

Python forces you to write structured code by using spaces to determine variable scope. You probably found this out pretty quickly. However, one very frustrating issue that often comes up is that Python *does* distinguish between tabs and spaces when determining spacing. For this reason you should always be consistent and use tabs *or* spaces, but not both. 

Jupyter automatically "expands" tabs into spaces, so it is generally not an issue inside of notebooks, but it can cause problems if you are copy/pasting code, or writing in a text editor that isn't configured for Python coding.

See below for an example:

In [ ]:
def hello_world():
    print("Hello World")
    print('...with space indent works.')
#	print('…with tab indent doesn’t') ## This line was copied in from a text editor.
    
hello_world()

### Numpy array copying

The underlying routines in Numpy are fast because they are written in C++, and Python is just used to access them efficiently. However, this leads to some quirky behavior. In particular, Numpy arrays work on "pointers" by default. This means that *all instances of an array operate on the same space in memory*. This can save a lot of coding and time if you know how it works, but it can also create some pretty insidious bugs through "non-local" modification of numpy arrays.

For example:

In [ ]:
import numpy as np
A = np.array([[1., 2., 3.],[4., 5., 6.],[7., 8., 9.]])
print(A)
b = A[0,:]
print(b)
b[0] = 10
print(b)
print(A)

You can avoid this behavior by "copying" arrays when assigning sub-arrays as variables:

In [ ]:
c = A[1,:].copy()
c[0] = 10
print(c)
print(A)

### Integer type casting

Another tricky thing in Python is the "integer" type. By default, any number without a decimal is an integer. In older versions of Python this caused problems with division since the rule was that the result of any operation between two integers must also be an integer, but that has been fixed in Python 3:

In [ ]:
x = 1
y = 2
print(x/y)

However, Numpy also uses specific types for arrays, and it follows the rule that assigning a variable to an array cannot change its type:

In [ ]:
A = np.array([1,2])
print(A)
print(A.dtype)
A[0] = 0.15
print(A)
print(A.dtype)

You can get around this by always using decimals when specifying numbers that you do not expect to remain integers:

In [ ]:
B = np.array([1.,2.])
B[0] = 0.15
print(B)
print(B.dtype)

or by explicitly defining the data type when you create the matrix:

In [ ]:
B = np.array([1,2], dtype='float64')
B[0] = 0.15
print(B)
print(B.dtype)