<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Tabs-and-spaces" data-toc-modified-id="Tabs-and-spaces-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Tabs and spaces</a></span></li><li><span><a href="#Numpy-array-copying" data-toc-modified-id="Numpy-array-copying-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Numpy array copying</a></span></li><li><span><a href="#Integer-type-casting" data-toc-modified-id="Integer-type-casting-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Integer type casting</a></span></li></ul></div>

# Python Tips, Tricks, and "gotchas"

Python is great once you get used to it, and is generally very similar to MATLAB and other scripting languages. However, there are a number of very tricky things that can cause issues and lots of frustration. I will collect the most insidious "gotchas" that come up in the course here in this notebook throughout the semester. If you have one to add, please let an instructor or teaching assistant know and we can include it.

## Tabs and spaces

Python forces you to write structured code by using spaces to determine variable scope. You probably found this out pretty quickly. However, one very frustrating issue that often comes up is that Python *does* distinguish between tabs and spaces when determining spacing. For this reason you should always be consistent and use tabs *or* spaces, but not both. 

Jupyter automatically "expands" tabs into spaces, so it is generally not an issue inside of notebooks, but it can cause problems if you are copy/pasting code, or writing in a text editor that isn't configured for Python coding.

See below for an example:

In [10]:
def hello_world():
    print("Hello World")
    print('...with space indent works.')
#	print('…with tab indent doesn’t') ## This line was copied in from a text editor.
    
hello_world()

Hello World
...with space indent works.


## Numpy array copying

The underlying routines in Numpy are fast because they are written in C++, and Python is just used to access them efficiently. However, this leads to some quirky behavior. In particular, Numpy arrays work on "pointers" by default. This means that *all instances of an array operate on the same space in memory*. This can save a lot of coding and time if you know how it works, but it can also create some pretty insidious bugs through "non-local" modification of numpy arrays.

For example:

In [16]:
import numpy as np
A = np.array([[1., 2., 3.],[4., 5., 6.],[7., 8., 9.]])
print(A)
b = A[0,:]
print(b)
b[0] = 10
print(b)
print(A)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[1. 2. 3.]
[[10.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


You can avoid this behavior by "copying" arrays when assigning sub-arrays as variables:

In [17]:
c = A[1,:].copy()
c[0] = 10
print(c)
print(A)

[10.  5.  6.]
[[10.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


## Integer type casting

Another tricky thing in Python is the "integer" type. By default, any number without a decimal is an integer. In older versions of Python this caused problems with division since the rule was that the result of any operation between two integers must also be an integer, but that has been fixed in Python 3:

In [18]:
x = 1
y = 2
print(x/y)

0.5


However, Numpy also uses specific types for arrays, and it follows the rule that assigning a variable to an array cannot change its type:

In [32]:
A = np.array([1,2])
print(A)
print(A.dtype)
A[0] = 0.15
print(A)
print(A.dtype)

[1 2]
int64
[0 2]
int64


You can get around this by always using decimals when specifying numbers that you do not expect to remain integers:

In [29]:
B = np.array([1.,2.])
B[0] = 0.15
print(B)
print(B.dtype)

[0.15 2.  ]
float64


or by explicitly defining the data type when you create the matrix:

In [33]:
B = np.array([1,2], dtype='float64')
B[0] = 0.15
print(B)
print(B.dtype)

[0.15 2.  ]
float64
